package firstgui;

/**
 *
 * @author Shruthi Routhu
 */
public class MainWindow extends javax.swing.JFrame {

    private MessageService msgService;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        msgService = new MessageService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namePrompt = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSayHello = new javax.swing.JButton();
        outputMesage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 0, 204));

        namePrompt.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        namePrompt.setForeground(new java.awt.Color(0, 0, 102));
        namePrompt.setText("Enter your name");

        btnSayHello.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnSayHello.setForeground(new java.awt.Color(102, 0, 0));
        btnSayHello.setText("Say Hello");
        btnSayHello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSayHelloActionPerformed(evt);
            }
        });

        outputMesage.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        outputMesage.setForeground(new java.awt.Color(0, 0, 102));
        outputMesage.setText("output");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(namePrompt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSayHello)
                    .addComponent(txtName)
                    .addComponent(outputMesage, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namePrompt)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSayHello)
                .addGap(18, 18, 18)
                .addComponent(outputMesage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSayHelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSayHelloActionPerformed
        String name = txtName.getText();
        String msg = msgService.createMessage(name);
        outputMesage.setText(msg);
    }//GEN-LAST:event_btnSayHelloActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSayHello;
    private javax.swing.JLabel namePrompt;
    private javax.swing.JLabel outputMesage;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
