/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firstgui;

/**
 *
 * @author Shruthi Routhu
 */
public class TempConverterGUI extends javax.swing.JFrame {

    private TempConverterService tempConverter;
    /**
     * Creates new form TemperatureCoverter
     */
    public TempConverterGUI() {
        initComponents();
        tempConverter = new TempConverterService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        promptFhTemp = new javax.swing.JLabel();
        txtFhTemp = new javax.swing.JTextField();
        FToCButton = new javax.swing.JButton();
        outputMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        promptFhTemp1 = new javax.swing.JLabel();
        txtCent = new javax.swing.JTextField();
        CtoFButton = new javax.swing.JButton();
        outputMessage2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        promptFhTemp.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        promptFhTemp.setForeground(new java.awt.Color(0, 0, 102));
        promptFhTemp.setText("Enter Fahrenheit");

        FToCButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        FToCButton.setForeground(new java.awt.Color(0, 0, 102));
        FToCButton.setText("Convert ");
        FToCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FToCButtonActionPerformed(evt);
            }
        });

        outputMessage.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        outputMessage.setForeground(new java.awt.Color(102, 0, 0));
        outputMessage.setText("Centigrade value");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Temparature Converter");

        promptFhTemp1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        promptFhTemp1.setForeground(new java.awt.Color(0, 0, 102));
        promptFhTemp1.setText("Enter Centigrade");

        CtoFButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        CtoFButton.setForeground(new java.awt.Color(0, 0, 102));
        CtoFButton.setText("Convert ");
        CtoFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CtoFButtonActionPerformed(evt);
            }
        });

        outputMessage2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        outputMessage2.setForeground(new java.awt.Color(102, 0, 0));
        outputMessage2.setText("Fahrenheit Value");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(promptFhTemp1)
                            .addComponent(promptFhTemp))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FToCButton)
                            .addComponent(txtFhTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputMessage)
                            .addComponent(txtCent, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CtoFButton)
                            .addComponent(outputMessage2))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promptFhTemp)
                    .addComponent(txtFhTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(FToCButton)
                .addGap(18, 18, 18)
                .addComponent(outputMessage)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promptFhTemp1)
                    .addComponent(txtCent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CtoFButton)
                .addGap(18, 18, 18)
                .addComponent(outputMessage2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FToCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FToCButtonActionPerformed
        String fTemp = txtFhTemp.getText();
        String value = tempConverter.convertFahrenheitToCentigrade(fTemp);
        outputMessage.setText(value);
    }//GEN-LAST:event_FToCButtonActionPerformed

    private void CtoFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CtoFButtonActionPerformed
        String CTemp = txtCent.getText();
        String value = tempConverter.convertCentigradeToFahrenheit(CTemp);
        outputMessage2.setText(value);
    }//GEN-LAST:event_CtoFButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CtoFButton;
    private javax.swing.JButton FToCButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel outputMessage;
    private javax.swing.JLabel outputMessage2;
    private javax.swing.JLabel promptFhTemp;
    private javax.swing.JLabel promptFhTemp1;
    private javax.swing.JTextField txtCent;
    private javax.swing.JTextField txtFhTemp;
    // End of variables declaration//GEN-END:variables
}
